# Generated by Django 3.1.7 on 2021-04-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'photobomb_users',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('PT', 'painting'), ('GRA', 'Graphics Design'), ('MUS', 'music'), ('PHO', 'Photography'), ('MOD', 'modeling')], default='PT', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photobomb.theuser')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
